version: '3'
networks:
  internal_network:
    driver: bridge
services:
  frontend:
    container_name: frontend
    restart: always
    networks: 
      - internal_network
    image: node:latest
    depends_on: 
      - webapi
    volumes:
      - ./FrontEnd:/usr/src/service
    environment:
      - NODE_ENV=development
      - REACT_APP_API_ENDPOINT=http://localhost:4000
    working_dir: /usr/src/service
    command: yarn start
    ports:
      - 3000:3000
  webapi:
    container_name: web_api
    restart: always
    networks: 
      - internal_network
    image: node:latest
    depends_on: 
      - redis
      - authenapi
      - resourceapi
    volumes:
      - ./WebApi:/usr/src/service
    environment:
      - NODE_ENV=development
      - AUTHEN_ENDPOINT=http://authenapi:3000
      - RESOURCE_ENDPOINT=http://resourceapi:3000
      - REDIS_ENDPOINT=redis://redis
      - JWT_SECRET=u7x!A%D*F-JaNdRgUkXp2s5v8y/B?E(H+KbPeShVmYq3t6w9z&X&F)J@NcQfTjWn
    working_dir: /usr/src/service
    command: yarn start
    ports:
      - 4000:4000
  authenapi:
    container_name: authen_api
    restart: always
    networks: 
      - internal_network
    image: node:latest
    depends_on: 
      - accountapi
    volumes:
      - ./AuthenApi:/usr/src/service
    environment:
      - NODE_ENV=development
      - ACCOUNT_ENDPOINT=http://accountapi:3000
      - JWT_SECRET=u7x!A%D*F-JaNdRgUkXp2s5v8y/B?E(H+KbPeShVmYq3t6w9z&X&F)J@NcQfTjWn
    working_dir: /usr/src/service
    command: yarn start
    ports:
      - 5001:3000
  accountapi:
    container_name: account_api
    restart: always
    networks: 
      - internal_network
    depends_on: 
      - mongo
    image: node:latest
    volumes:
      - ./AccountApi:/usr/src/service
    environment:
      - NODE_ENV=development
      - MONGO_ENDPOINT=mongodb://mongo/sample
      - MONGO_USER=root
      - MONGO_PASSWORD=password
    working_dir: /usr/src/service
    command: yarn start
    ports:
      - 5002:3000
  resourceapi:
    container_name: resource_api
    restart: always
    networks: 
      - internal_network
    image: node:latest
    volumes:
      - ./ResourceApi:/usr/src/service
    environment:
      - NODE_ENV=development
      - ACCOUNT_ENDPOINT=http://accountapi:5002
      - JWT_SECRET=u7x!A%D*F-JaNdRgUkXp2s5v8y/B?E(H+KbPeShVmYq3t6w9z&X&F)J@NcQfTjWn
    working_dir: /usr/src/service
    command: yarn start
    ports:
      - 5003:3000
  mongo:
    container_name: mongo
    restart: always
    networks: 
      - internal_network
    build: ./MongoDB/
    volumes: 
      - ./MongoDB/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
  redis:
    container_name: redis
    restart: always
    networks:
      - internal_network
    build: ./Redis/
    ports:
      - 6379:6379